import LegalDocument from '@/components/LegalDocument';

const sections = [
  { heading: 'Information we collect', paragraphs: ['We collect account information such as your name, email address, optional phone number, password hash, and short-lived email verification records. We also store the expenses, categories, budget limits, spending totals, and notifications you choose to create.', 'We may process basic technical information needed to operate and secure the service, such as request timestamps, authentication events, error logs, device or browser details, and network identifiers.'] },
  { heading: 'How we use information', paragraphs: ['We use your information to create and authenticate your account, deliver the tracker’s features, calculate budget progress, send requested verification emails, generate alerts, support users, prevent abuse, diagnose failures, and improve reliability. We do not sell personal information.'] },
  { heading: 'When information is shared', paragraphs: ['Information is shared only with infrastructure and email-delivery providers that help operate SmartBudget, when you direct us to share it, or when disclosure is required to comply with law or protect users and the service. Providers receive only the access needed to perform their role.'] },
  { heading: 'Security and retention', paragraphs: ['Passwords and verification codes are stored as one-way hashes. Verification challenges expire after a short period, and authenticated requests use signed access tokens. No system is completely secure, so you should use a unique password and protect access to your email account.', 'We retain account and financial-tracking data while your account is active and for a limited period when needed for recovery, security, legal compliance, or dispute resolution. Retention rules should be finalized before commercial launch.'] },
  { heading: 'Your choices', paragraphs: ['You can review and update your name, email, and phone number in the profile interface. Email changes require confirmation at the new address. Phone changes currently do not use SMS verification; adding phone verification is a known future security improvement. You may contact us to request account-data access, correction, or deletion where applicable.'] },
  { heading: 'Children and international use', paragraphs: ['SmartBudget is not directed to children under 13, and we do not knowingly collect their personal information. Privacy rights vary by location; additional regional notices and controls may be required before broader release.'] },
  { heading: 'Changes and contact', paragraphs: ['We may update this policy as SmartBudget evolves. Material changes will be communicated through the service or account email when appropriate. Privacy questions can be sent to the service contact address shown in the application. This placeholder policy should be reviewed by qualified counsel before commercial launch.'] },
];

const Privacy = () => <LegalDocument title="Privacy Policy" intro="This policy describes the information SmartBudget processes, why it is needed, and the choices available to account holders." sections={sections} />;
export default Privacy;
